# Generated by Django 2.0.3 on 2020-07-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncidentForm', '0002_auto_20200710_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='reportedBy',
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.IntegerField(choices=[(1, 'Corporate Headoffice'), (2, 'Operations Department'), (3, 'Work Station'), (4, 'Marketing Division')]),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0),
        ),
    ]
