# Generated by Django 2.0.3 on 2020-07-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncidentForm', '0003_auto_20200710_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reportedBy',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
