# Generated by Django 2.0.3 on 2020-07-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncidentForm', '0004_incident_reportedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='subIncidentTypes',
            field=models.CharField(blank=True, choices=[('1', 'Environmental Incident'), ('2', 'Injury/Illness'), ('3', 'Property Damage'), ('4', 'Vehicle')], max_length=10, null=True),
        ),
    ]
