# Generated by Django 2.0.3 on 2020-07-10 08:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncidentForm', '0005_auto_20200710_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='subIncidentTypes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), blank=True, choices=[('1', 'Environmental Incident'), ('2', 'Injury/Illness'), ('3', 'Property Damage'), ('4', 'Vehicle')], null=True, size=None),
        ),
    ]
