# Generated by Django 2.0.3 on 2020-07-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncidentForm', '0006_auto_20200710_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='actionTaken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
