# Generated by Django 2.0.3 on 2020-07-10 10:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('IncidentForm', '0007_auto_20200710_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='subIncidentTypes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Environmental Incident'), ('2', 'Injury/Illness'), ('3', 'Property Damage'), ('4', 'Vehicle')], default='1', max_length=7),
            preserve_default=False,
        ),
    ]
